# Generated by Django 4.2.5 on 2023-09-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0005_alter_moreinfo_genre_movierating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Horror'), (3, 'Comedia'), (4, 'Sci-fi'), (2, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('movies', models.ManyToManyField(to='moviesweb.movie')),
            ],
        ),
    ]
