# Generated by Django 4.2.5 on 2023-09-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesweb', '0006_alter_moreinfo_genre_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(related_name='actors', to='moviesweb.movie'),
        ),
        migrations.AlterField(
            model_name='moreinfo',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Sci-fi'), (2, 'Drama'), (3, 'Comedy'), (1, 'Horror'), (0, 'Other')], default=0),
        ),
    ]
